version: '3'
services:
  # 3000
  client:
    restart: always
    image: ermiry/videos-stream-client:latest

  # 3001
  upload:
    restart: always
    image: ermiry/videos-upload-client:latest

  # 5001
  videos:
    restart: always
    image: ermiry/videos-service:test
    ports:
      - 5001
    volumes:
      - ${UPLOADS}:/home/uploads
    environment:
      - RUNTIME=test
      - PORT=5001
      - CERVER_RECEIVE_BUFFER_SIZE=16384
      - CERVER_TH_THREADS=4
      - CERVER_CONNECTION_QUEUE=4
      - MONGO_APP_NAME=upload
      - MONGO_DB=videos
      - MONGO_URI=mongodb://upload:password@mongo:27017/videos
  
  # 5002
  service:
    restart: always
    image: ermiry/stream-service:test
    ports:
      - 5002
    volumes:
      - ${UPLOADS}:/home/uploads
    environment:
      - RUNTIME=test
      - PORT=5002
      - CERVER_RECEIVE_BUFFER_SIZE=4096
      - CERVER_TH_THREADS=4
      - CERVER_CONNECTION_QUEUE=4
      - MONGO_APP_NAME=stream
      - MONGO_DB=videos
      - MONGO_URI=mongodb://stream:password@mongo:27017/videos

  nginx:
    restart: always
    image: ermiry/videos-nginx:test
    ports:
      - '80:80'

networks:
  default:
    external:
      name: videos
