version: '3'
services:
  # 3000
  client:
    tty: true
    build:
      dockerfile: Dockerfile.dev
      context: ./videos-upload-client
    volumes:
      - ./videos-upload-client:/home/videos

  nginx:
    restart: always
    image: ermiry/videos-nginx:development
    ports:
      - '80:80'

networks:
  default:
    external:
      name: videos
